### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by NickStrupat** [ekonwlo/Common.Net.REST.ArcGIS#1]
Hi Konrad,

Thanks for the great libraries. You put in a lot of work across the bunch of them.

Do you have a plan to release them as .NET Standard packages on NuGet? In particular, this one and its dependencies.

PS, love the photo haha

**Comment by ekonwlo** [comment]
Hi,

I thought about it and maybe in the far future I'll do this, however recently I have no time for working on this.
First of all I wanted to add tests and automate builds somehow in jenkins or something like this.

Cheers

**Comment by NickStrupat** [comment]
Thank you for your quick response.

.NET Core 2.0 is supposed to have the ability to consume .NET Framework libraries if they are compatible with .NET Standard 2.0. This likely means you won't need to port your libraries to .NET Standard once 2.0 is out :)
